from typing import Protocol, List
from features.items.domain.entities.item import Item

class ItemRepositoryPort(Protocol):
    def get_all(self) -> List[Item]: ...
    def get_by_id(self, item_id: str) -> Item | None: ...
    def create(self, name: str) -> Item: ...
    def update(self, item_id, name: str) -> Item: ...
    def delete(self, item_id: str) -> bool: ...